# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.3
      brew_packages: nim
    - os: osx
      osx_image: xcode7.3
      brew_packages: nim

addons:
  apt:
    packages:
      - nim
